Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Found 45 test(s).
Operations to perform:
  Synchronize unmigrated apps: messages, rest_framework, staticfiles
  Apply all migrations: address, admin, auth, authtoken, contenttypes, courses, sessions, users
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying address.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying users.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying courses.0001_initial... OK
  Applying courses.0002_initial... OK
  Applying sessions.0001_initial... OK
System check identified no issues (0 silenced).
test_duplicate_email_user_creation_422 (test_api.TestAccountsRoutesWithoutAuthentication) ... ERROR
test_instructor_user_creation_201 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_list_users_by_instructor_200 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_list_users_by_student_403 (test_api.TestAccountsRoutesWithoutAuthentication) ... FAIL
test_list_users_with_no_token_401 (test_api.TestAccountsRoutesWithoutAuthentication) ... FAIL
test_login_success_200 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_login_with_invalid_credentials_401 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_login_with_wrong_fields_400 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_student_user_creation_201 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_wrong_data_user_creation_400 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_address_creation_200 (test_api.TestAddress) ... FAIL
test_address_creation_already_exists_200 (test_api.TestAddress) ... FAIL
test_address_creation_wrong_data_400 (test_api.TestAddress) ... ok
test_delete_course_by_instructor_204 (test_api.TestCourseDelete) ... ERROR
test_delete_course_by_no_user_401 (test_api.TestCourseDelete) ... ERROR
test_delete_course_by_student_403 (test_api.TestCourseDelete) ... ERROR
test_delete_course_with_invalid_course_id_404 (test_api.TestCourseDelete) ... ERROR
test_course_creation_by_instructor_201 (test_api.TestCoursesCreation) ... ERROR
test_course_creation_by_no_user_401 (test_api.TestCoursesCreation) ... ERROR
test_course_creation_by_student_403 (test_api.TestCoursesCreation) ... ERROR
test_course_creation_duplicate_name_422 (test_api.TestCoursesCreation) ... ERROR
test_course_creation_wrong_data_400 (test_api.TestCoursesCreation) ... ERROR
test_list_courses_200 (test_api.TestCoursesCreation) ... ERROR
test_retrieve_invalid_course_404 (test_api.TestCoursesCreation) ... ERROR
test_retrieve_valid_course_200 (test_api.TestCoursesCreation) ... ERROR
test_register_instructor_course_by_instructor_200 (test_api.TestCoursesRegister) ... ERROR
test_register_instructor_course_by_no_user_401 (test_api.TestCoursesRegister) ... ERROR
test_register_instructor_course_by_student_403 (test_api.TestCoursesRegister) ... ERROR
test_register_instructor_course_with_invalid_id_404 (test_api.TestCoursesRegister) ... ERROR
test_register_instructor_course_with_student_id_422 (test_api.TestCoursesRegister) ... ERROR
test_register_instructor_course_with_wrong_field_400 (test_api.TestCoursesRegister) ... ERROR
test_register_instructor_course_wrong_courseId_404 (test_api.TestCoursesRegister) ... ERROR
test_register_students_course_by_intructor_200 (test_api.TestCoursesRegister) ... ERROR
test_register_students_course_by_no_user_401 (test_api.TestCoursesRegister) ... ERROR
test_register_students_course_by_student_403 (test_api.TestCoursesRegister) ... ERROR
test_register_students_course_invalid_course_id_404 (test_api.TestCoursesRegister) ... ERROR
test_register_students_course_with_instructor_id_422 (test_api.TestCoursesRegister) ... ERROR
test_register_students_course_with_invalid_student_id_404 (test_api.TestCoursesRegister) ... ERROR
test_register_students_course_with_wrong_field_400 (test_api.TestCoursesRegister) ... ERROR
test_register_students_course_with_wrong_field_type_400 (test_api.TestCoursesRegister) ... ERROR
test_update_course_by_instructor_200 (test_api.TestCoursesUpdate) ... ERROR
test_update_course_by_no_user_401 (test_api.TestCoursesUpdate) ... ERROR
test_update_course_by_student_403 (test_api.TestCoursesUpdate) ... ERROR
test_update_course_with_conflict_422 (test_api.TestCoursesUpdate) ... ERROR
test_update_invalid_course_404 (test_api.TestCoursesUpdate) ... ERROR

======================================================================
ERROR: test_duplicate_email_user_creation_422 (test_api.TestAccountsRoutesWithoutAuthentication)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 87, in test_duplicate_email_user_creation_422
    token = self.client.post("/api/login/", self.instructor_login_data, format="json").json()["token"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/test.py", line 296, in post
    response = super().post(
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/test.py", line 210, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/test.py", line 234, in generic
    return super().generic(
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 541, in generic
    return self.request(**r)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/test.py", line 286, in request
    return super().request(**kwargs)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/test.py", line 238, in request
    request = super().request(**kwargs)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 810, in request
    self.check_exception(response)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 663, in check_exception
    raise exc_value
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/estevan/dev/Q4/e10-kanvas/users/views.py", line 48, in post
    user = authenticate(email=serialized.data["email"], password=serialized.data["password"])
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/contrib/auth/backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 46, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 83, in _execute
    self.db.validate_no_broken_transaction()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 480, in validate_no_broken_transaction
    raise TransactionManagementError(
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

======================================================================
ERROR: test_delete_course_by_instructor_204 (test_api.TestCourseDelete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 1072, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_delete_course_by_no_user_401 (test_api.TestCourseDelete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 1072, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_delete_course_by_student_403 (test_api.TestCourseDelete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 1072, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_delete_course_with_invalid_course_id_404 (test_api.TestCourseDelete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 1072, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_course_creation_by_instructor_201 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 252, in test_course_creation_by_instructor_201
    output = response.json()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_course_creation_by_no_user_401 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 282, in test_course_creation_by_no_user_401
    output = response.json()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_course_creation_by_student_403 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 268, in test_course_creation_by_student_403
    output = response.json()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_course_creation_duplicate_name_422 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 300, in test_course_creation_duplicate_name_422
    output = response.json()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_course_creation_wrong_data_400 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 317, in test_course_creation_wrong_data_400
    output = response.json()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_list_courses_200 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 330, in test_list_courses_200
    output = response.json()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_retrieve_invalid_course_404 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 373, in test_retrieve_invalid_course_404
    output = response.json()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_retrieve_valid_course_200 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 355, in test_retrieve_valid_course_200
    course = self.client.post("/api/courses/", self.course_data, format="json").json()
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_by_instructor_200 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_by_no_user_401 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_by_student_403 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_invalid_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_student_id_422 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_wrong_field_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_wrong_courseId_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_intructor_200 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_no_user_401 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_student_403 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_invalid_course_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_instructor_id_422 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_invalid_student_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_wrong_field_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_wrong_field_type_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 609, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_update_course_by_instructor_200 (test_api.TestCoursesUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 409, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_update_course_by_no_user_401 (test_api.TestCoursesUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 409, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_update_course_by_student_403 (test_api.TestCoursesUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 409, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_update_course_with_conflict_422 (test_api.TestCoursesUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 409, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_update_invalid_course_404 (test_api.TestCoursesUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 409, in setUp
    self.course_id = self.client.post("/api/courses/", self.course_data, format="json").json()["uuid"]
  File "/home/estevan/dev/Q4/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
FAIL: test_list_users_by_student_403 (test_api.TestAccountsRoutesWithoutAuthentication)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 177, in test_list_users_by_student_403
    self.assertEqual(response.status_code, 403)
AssertionError: 200 != 403

======================================================================
FAIL: test_list_users_with_no_token_401 (test_api.TestAccountsRoutesWithoutAuthentication)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 185, in test_list_users_with_no_token_401
    self.assertEqual(response.status_code, 401)
AssertionError: 200 != 401

======================================================================
FAIL: test_address_creation_200 (test_api.TestAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 1225, in test_address_creation_200
    self.assertEqual(response.status_code, 200)
AssertionError: 201 != 200

======================================================================
FAIL: test_address_creation_already_exists_200 (test_api.TestAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/estevan/dev/Q4/e10-kanvas/test_api.py", line 1248, in test_address_creation_already_exists_200
    self.assertEqual(response.status_code, 200)
AssertionError: 201 != 200

----------------------------------------------------------------------
Ran 45 tests in 13.546s

FAILED (failures=4, errors=33)
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
